# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginandregistration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friended',
            field=models.ManyToManyField(related_name='_user_friended_+', to='loginandregistration.User'),
        ),
    ]
